#!/bin/bash
# Download all Texas GLO DRGR Reports - Organized by Disaster Category
# Source: https://www.glo.texas.gov/disaster-recovery/grant-administration/grant-administration-reporting/hud-drgr-qpr-reports

BASE_URL="https://www.glo.texas.gov"
OUTPUT_DIR="DRGR_Reports"

mkdir -p "$OUTPUT_DIR"

# Function to download PDF
download_pdf() {
    local path="$1"
    local category="$2"
    local filename=$(basename "$path")
    local dir="$OUTPUT_DIR/$category"

    mkdir -p "$dir"

    # Clean filename (remove URL encoding)
    local clean_filename=$(echo "$filename" | sed 's/%20/ /g' | sed 's/%28/(/g' | sed 's/%29/)/g')

    if [ -f "$dir/$clean_filename" ]; then
        echo "Skipping (exists): $clean_filename"
        return
    fi

    echo "Downloading: $category/$clean_filename"
    curl -sS -L -o "$dir/$clean_filename" "${BASE_URL}${path}"
    sleep 0.3  # Be nice to the server
}

echo "=== Downloading Texas GLO DRGR Reports ==="
echo ""

# 2024 Disasters
echo "--- 2024 Disasters ---"
download_pdf "/sites/default/files/2026-01/drgr-2024-disasters-2025-q4.pdf" "2024_Disasters"

# 2019 Disasters Grant Performance Reports
echo "--- 2019 Disasters Grant Performance ---"
download_pdf "/sites/default/files/2025-11/2019-disasters-2025-q3.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/2025-07/2019-disasters-2025-q2.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/2025-05/2019-disasters-2025-q1.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/2025-01/2019-disasters-2024-q4_0.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/2024-12/2019-disasters-2024-q3.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/20241018/2019-disasters-2024-q2.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2024-q1.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2023-q4.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2023-q3.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2023-q2.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disastersgrantreport-2023-q1.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2022-q4.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2022-q3.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2022-q2.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2022-q1.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2021-q4.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2019-disasters-2021-q3.pdf" "2019_Disasters_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2021-q2.pdf" "2019_Disasters_Performance"

# 2019 Disasters DRGR Action Plan Reports
echo "--- 2019 Disasters Action Plan ---"
download_pdf "/sites/default/files/2026-01/drgr-2019-disasters-2025-q4.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/2025-11/drgr-2019-disasters-2025-q3.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-2019-disasters-2025-q2.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/2025-01/drgr-2019-disasters-2024-q4%20%282%29.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/2024-11/drgr-2019-disasters-2024-q3.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/20241018/drgr-2018-floods-2024-q2.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2024-q1.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2023-q4.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2023-q3.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2023-q2.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2023-q1.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2022-q4.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2022-q3.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2022-q2.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2022-q1.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2021-q4.pdf" "2019_Disasters_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2019-disasters-2021-q3.pdf" "2019_Disasters_ActionPlan"

# 2018 South Texas Floods Performance Reports
echo "--- 2018 South Texas Floods Performance ---"
download_pdf "/sites/default/files/2025-11/2018-floods-2025-q3.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/2025-07/2018-floods-2025-q2.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/2025-05/2018-floods-2025-q1.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/2025-01/2018-floods-2024-q4.pd_.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/2024-12/2018-floods-2024-q3.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/2024-10/2018-floods-2024-q2.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2024-q1.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2023-q4.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2023-q3.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2023-q2.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floodsgrantreport-2023-q1.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2022-q4.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2022-q3.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2022-q2.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2022-q1.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2021-q4.pdf" "2018_Floods_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/2018-floods-2021-q3.pdf" "2018_Floods_Performance"

# 2018 South Texas Floods Action Plan Reports
echo "--- 2018 South Texas Floods Action Plan ---"
download_pdf "/sites/default/files/2026-01/drgr-2018-floods-2025-q4.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/2025-11/drgr-2018-floods-2025-q3.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-2018-floods-2025-q2.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-2018-floods-2025-q1.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/2025-01/drgr-2018-floods-2024-q4%20%281%29.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/2024-11/drgr-2018-floods-2024-q3.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/20241018/drgr-2018-floods-2024-q2.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2024-q1.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2023-q4.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2023-q3.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2023-q2.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2023-q1.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2022-q4.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-floods-2022-q3.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-south-texas-floods-2022-q2.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-south-texas-floods-2022-q1.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-south-texas-floods-2021-q4.pdf" "2018_Floods_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-2018-2019/drgr-2018-south-texas-floods-2021-q3.pdf" "2018_Floods_ActionPlan"

# CDBG-DR and MIT Expenditure Reports
echo "--- CDBG-DR/MIT Expenditure Reports ---"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/cdbg-dr-and-mit-timely-expenditure-report-2020-4q.pdf" "Expenditure_Reports"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/cdbg-dr-mit-expenditures-report-2020-3q.pdf" "Expenditure_Reports"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/cdbg-dr-mit-expenditures-report-2020-2q.pdf" "Expenditure_Reports"

# Mitigation Grant Performance Reports
echo "--- Mitigation Performance ---"
download_pdf "/sites/default/files/2025-11/mit-2025-q3.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/2025-07/mit-2025-q2.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/2025-05/mit-2025-q1.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/2025-01/mit-2024-q4.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/2024-12/mit-2024-q3.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/20241018/mit-2024-q2.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2024-q1.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2023-q4.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2023-q3.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2023-q2.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mitigationgrantreport-2023-q1.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2022-q4.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2022-q3.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2022-q2.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2022-q1.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2021-q4.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2021-q3.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2021-q2.pdf" "Mitigation_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/mit-2021-q1.pdf" "Mitigation_Performance"

# Mitigation DRGR Action Plan Reports
echo "--- Mitigation Action Plan ---"
download_pdf "/sites/default/files/2026-01/drgr-mit-2025-q4.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/2025-11/drgr-mit-2025-q3.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-mit-2025-q2.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/2025-04/drgr-mit-2025-q1.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/2025-01/drgr-mit-2024-q4%20%281%29.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/2024-11/drgr-mit-2024-q3.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/20241018/drgr-mit-2024-q2.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2024-q1.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2023-q4.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2023-q3.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2023-q2.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2023-q1.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2022-q4.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2022-q3.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2022-q2.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2022-q1.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2021-q4.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2021-q3.pdf" "Mitigation_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-mitigation/drgr-mit-2021-q1.pdf" "Mitigation_ActionPlan"

# Hurricane Harvey $5B Performance Reports
echo "--- Hurricane Harvey 5B Performance ---"
download_pdf "/sites/default/files/2025-11/h5b-2025-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/2025-07/h5b-2025-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/2025-05/h5b-2025-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/2025-01/h5b-2024-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/2024-11/drgr-h5b-2024-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/20241018/h5b-2024-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2024-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2023-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2023-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2023-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/harveygrantperformance-2023-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2022-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2022-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2022-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2022-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2021-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2021-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2021-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2021-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2020-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2020-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2020-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2020-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2019-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2019-q3.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2019-q2.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2019-q1.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/h5b-2018-q4.pdf" "Harvey_5B_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh5b-2018-q3.pdf" "Harvey_5B_Performance"

# Hurricane Harvey $5B Action Plan Reports
echo "--- Hurricane Harvey 5B Action Plan ---"
download_pdf "/sites/default/files/2026-01/drgr-h5b-2025-q4.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/2025-11/drgr-h5b-2025-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-h5b-2025-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/2025-04/drgr-h5b-2025-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/2025-01/drgr-h5b-2024-q4%20%281%29.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/2024-11/drgr-h5b-2024-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/20241018/drgr-h5b-2024-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2024-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2023-q4.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2023-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2023-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2023-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2022-q4.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-h5b-2022-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2022-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2022-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2021-q4.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2021-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2021-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2021-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2020-q4.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-2020-q3.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-ap-2020-q2.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-ap-2020-q1.pdf" "Harvey_5B_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh5b-ap-2019-q4.pdf" "Harvey_5B_ActionPlan"

# Hurricane Harvey $57.8M Performance Reports
echo "--- Hurricane Harvey 57M Performance ---"
download_pdf "/sites/default/files/2025-11/hh57m-2025-q3.pdf.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/2025-05/hh57m-2025-q1.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/2025-01/hh57m-2024-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/2024-11/drgr-hh57m-2024-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/20241018/hh57m-2024-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2024-q1.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2023-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2023-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2023-q1.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2022-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2022-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2022-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2022-q1.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2021-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2021-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2021-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2021-q11.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2020-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2020-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2020-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2020-q1.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2019-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2019-q3.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2019-q2.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-ap-2019-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2018-q4.pdf" "Harvey_57M_Performance"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-2018-q3.pdf" "Harvey_57M_Performance"

# Hurricane Harvey $57.8M Action Plan Reports
echo "--- Hurricane Harvey 57M Action Plan ---"
download_pdf "/sites/default/files/2026-01/drgr-hh57m-2025-q4.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/2025-11/drgr-hh57m-2025-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/2025-07/drgr-hh57m-2025-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/2025-04/drgr-hh57m-2025-q1_0.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/2025-01/drgr-hh57m-2024-q4%20%282%29.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/2024-11/drgr-hh57m-2024-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/20241018/drgr-hh57m-2024-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2024-q1.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2023-q4.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2023-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2023-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2023-q1.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2022-q4.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2022-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2022-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2022-q1.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2021-q4.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2021-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-ap-2021-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2021-q1.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2020-q4.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-2020-q3.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2020-q2.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/drgr-hh57m-ap-2020-q1.pdf" "Harvey_57M_ActionPlan"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-harvey/hh57m-ap-2019-q4.pdf" "Harvey_57M_ActionPlan"

# 2016 Floods Grant Performance Reports
echo "--- 2016 Floods Performance ---"
download_pdf "/sites/default/files/2025-11/16f-2025-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/2025-07/16f-2025-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/2025-05/16f-2025-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/2025-01/16f-2024-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/2024-11/16f-2024-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/20241018/16f-2024-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2024-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2023-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2023-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2023-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2023-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2022-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2022-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2022-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2022-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2021-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2021-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2021-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2021-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2020-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2020-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2020-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2020-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/16f-2019-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2019-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2019-q2.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2019-q1.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2018-q4.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2018-q3.pdf" "2016_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f16-2018-q2.pdf" "2016_Floods"

# 2015 Floods Grant Performance Reports
echo "--- 2015 Floods Performance ---"
download_pdf "/sites/default/files/2025-11/15f-2025-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/2025-07/15f-2025-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/2025-05/15f-2025-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/2025-01/15f-2024-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/2024-11/15f-2024-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/20241018/15f-2024-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2024-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2023-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2023-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2023-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2022-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2022-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2022-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2022-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2021-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2021-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2021-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2021-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2020-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2020-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2020-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2020-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2019-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2019-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2019-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2019-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/15f-2018-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2018-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2018-q2.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2018-q1.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2017-q4.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2017-q3.pdf" "2015_Floods"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-15-16-floods/f15-2017-q2.pdf" "2015_Floods"

# Hurricane Ike/Dolly Grant Performance Reports
echo "--- Hurricane Ike/Dolly ---"
download_pdf "/sites/default/files/2025-11/ike-2025-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/2025-07/ike-2025-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/2025-05/ike-2025-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/2025-01/ike-2024-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/2024-11/ike-2024-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/20241018/ike-2024-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2024-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2023-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2023-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2023-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2023-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2022-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2022-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2022-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2022-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2021-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2021-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2021-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2021-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2020-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2020-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2020-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2020-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2019-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2019-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2019-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2019-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2018-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2018-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2018-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2018-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2017-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2017-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2017-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2017-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2016-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2016-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2016-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2016-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2015-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2015-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2015-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2015-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2014-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2014-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2014-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2014-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2013-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2013-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2013-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2013-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2012-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2012-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2012-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2012-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2011-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2011-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2011-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2011-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2010-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2010-q3.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2010-q2.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2010-q1.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2009-q4.pdf" "Hurricane_Ike"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-ike/ike-2009-q3.pdf" "Hurricane_Ike"

# Hurricane Rita 1 Grant Performance Reports
echo "--- Hurricane Rita 1 ---"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2016-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2016-q3.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2016-q2.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2016-q1.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2015-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2015-q3.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2015-q2.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2015-q1.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2014-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2014-q3.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2014-q2.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2014-q1.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2013-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2013-q3.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2013-q2.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2013-q1.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2012-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2012-q3.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2012-q2.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2012-q1.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2011-q4.pdf" "Hurricane_Rita1"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita1/rita1-2011-q3.pdf" "Hurricane_Rita1"

# Hurricane Rita 2 Grant Performance Reports
echo "--- Hurricane Rita 2 ---"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2017-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2017-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2017-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2017-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2016-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2016-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2016-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2016-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2015-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2015-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2015-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2015-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2014-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2014-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2014-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2014-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2013-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2013-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2013-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2013-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2012-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2012-q3.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2012-q2.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2012-q1.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2011-q4.pdf" "Hurricane_Rita2"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-rita2/rita2-2011-q3.pdf" "Hurricane_Rita2"

# Wildfire I Grant Performance Reports
echo "--- Wildfire I ---"
download_pdf "/sites/default/files/2025-11/wf1-2025-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/2025-07/wf1-2025-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/2025-05/wf1-2025-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/2025-01/wf1-2024-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/2024-11/wf1-2024-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/20241018/wf1-2024-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2024-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2023-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2023-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2023-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2023-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2022-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2022-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2022-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2022-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2021-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2021-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2021-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2021-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2020-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2020-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2020-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2020-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2019-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2019-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2019-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2019-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2018-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2018-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2018-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2018-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2017-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2017-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2017-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2017-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2016-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2016-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2016-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2016-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2015-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2015-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2015-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2015-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2014-q4.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2014-q3.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2014-q2.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2014-q1.pdf" "Wildfire_I"
download_pdf "/sites/default/files/resources/cdr/documents/grant-administration/reports/hud-drgr-qpr/drgr-wildfire-1/wf1-2013-q3.pdf" "Wildfire_I"

echo ""
echo "=== Download Complete ==="
echo "Reports saved to: $OUTPUT_DIR"
echo ""
echo "Directory structure:"
find "$OUTPUT_DIR" -type d | sort
echo ""
find "$OUTPUT_DIR" -name "*.pdf" | wc -l | xargs echo "Total PDFs downloaded:"
