#!/usr/bin/env python3
"""
Run SEM estimations on the adapter outputs created in Phase 1.

This script is a first-pass SEM runner for this repository. It:

- Loads one of the adapter-generated quarter-panel CSVs.
- Normalizes adapter column names to SEM specification variables.
- Fits a model from `capacity_sem.models.sem_specifications`.
- Writes estimates, fit stats, and diagnostics under `outputs/sem/texas/results/`.

Phase 2 default:
- model: adapter_progress_rate
- panel: disaster
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import sys
from typing import Any, Dict, List, Optional, Sequence

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT_DIR = ROOT / "outputs" / "sem" / "texas"
DEFAULT_OUTPUT_DIR = DEFAULT_INPUT_DIR / "results"

# Keep package imports stable when run as a script from repository root.
SRC_ROOT = ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from capacity_sem.models.sem_diagnostics import evaluate_model_fit, summarize_fit
from capacity_sem.models.sem_fitting import fit_and_summarize
from capacity_sem.models.sem_specifications import (
    MODEL_REGISTRY,
    get_model_description,
    get_model_spec,
)

VARIABLE_ALIAS = {
    "ratio_disbursed_to_obligated": "Ratio_disbursed_to_obligated",
    "ratio_expended_to_disbursed": "Ratio_expended_to_disbursed",
    "duration_of_completion": "Duration_of_completion",
    "timeliness": "Timeliness",
    "progress_rate": "Progress_Rate",
    "spending_cv": "Spending_CV",
    "completion_pct": "Completion_Pct",
}


def _default_input_path(panel_level: str) -> Path:
    return DEFAULT_INPUT_DIR / f"panel_{panel_level}_quarter_sem_estimation_input.csv"


def _build_output_prefix(panel_level: str, model: str, subset: str) -> str:
    return f"panel-{panel_level}_model-{model}_subset-{subset}"


def _to_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


@dataclass(frozen=True)
class EstimationArtifacts:
    """Files generated by a single SEM run."""

    estimates_path: Path
    fit_stats_path: Path
    diagnostics_path: Path
    manifest_path: Path


def _normalize_panel_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Normalize adapter columns to the naming expected by SEM specs.

    The adapter uses lowercase snake_case; the legacy SEM specs use title-case.
    """
    normalized = df.copy()
    for source, target in VARIABLE_ALIAS.items():
        if source in normalized.columns and target not in normalized.columns:
            normalized[target] = normalized[source]
    for target in [*VARIABLE_ALIAS.values()]:
        if target in normalized.columns:
            normalized[target] = pd.to_numeric(normalized[target], errors="coerce")

    # Derivations helpful across several candidate specs.
    if "Ratio_obligated_funds_fully_expended" not in normalized.columns:
        if {"sum_expended_usd", "sum_obligated_usd"} <= set(normalized.columns):
            denom = pd.to_numeric(normalized["sum_obligated_usd"], errors="coerce")
            num = pd.to_numeric(normalized["sum_expended_usd"], errors="coerce")
            with np.errstate(divide="ignore", invalid="ignore"):
                normalized["Ratio_obligated_funds_fully_expended"] = num / denom
        else:
            normalized["Ratio_obligated_funds_fully_expended"] = np.nan

    # Spending_CV is now derived in the adapter; keep fallback for older inputs.
    if "Spending_CV" not in normalized.columns:
        normalized["Spending_CV"] = np.nan

    # Historical spec expects this outcome as an observed variance statistic.
    if "Quarter_by_quarter_variance_expended" not in normalized.columns:
        normalized["Quarter_by_quarter_variance_expended"] = np.nan

    # Replace infinities before fitting; sempy will drop any remaining NaNs by model.
    normalized = normalized.replace([np.inf, -np.inf], np.nan)
    return normalized


def _required_variables(model_spec: str) -> List[str]:
    """
    Extract likely observed variables from a semopy/Lavaan specification.

    This uses the same style regex tokenization used in sem_fitting.py.
    """
    tokens = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", model_spec))
    return sorted(
        [
            token
            for token in tokens
            if token[0].isupper()
            and "_" in token
            and "Model" not in token
            and token not in {"CFI", "TLI", "RMSEA", "AIC", "BIC"}
        ]
    )


def _verify_inputs(df: pd.DataFrame, model_type: str) -> None:
    model_spec = get_model_spec(model_type)
    required = _required_variables(model_spec)
    missing = [col for col in required if col not in df.columns]
    if not missing:
        return

    known = set(df.columns)
    alias_hints = sorted(c for c in required if c.lower() in known)
    if alias_hints:
        # If a user somehow passes an un-normalized file, suggest what can be fixed.
        print("Note: found case-insensitive matches for required fields (lowercase exists):")
        for req in alias_hints:
            print(f"  {req.lower()} -> {req}")
    raise ValueError(
        "Model inputs are missing required columns:\n"
        f"  {', '.join(missing)}\n\n"
        "Run build_sem_estimation_inputs.py first (phase 1) and keep using "
        "the default phase-2-compatible column aliases."
    )


def run_estimation(
    input_path: Path,
    panel_level: str,
    model_type: str,
    subset: str,
    overwrite: bool,
    output_dir: Path,
    min_observations: int,
) -> EstimationArtifacts:
    if not input_path.exists():
        raise FileNotFoundError(f"SEM input not found: {input_path}")

    if model_type not in MODEL_REGISTRY:
        raise ValueError(f"Unknown model_type='{model_type}'.")

    print(f"Loading SEM input: {input_path}")
    df = pd.read_csv(input_path)
    df = _normalize_panel_columns(df)
    _verify_inputs(df, model_type)

    model_spec = get_model_spec(model_type)
    required_vars = _required_variables(model_spec)
    complete_n = len(df.dropna(subset=required_vars))
    if complete_n < min_observations:
        raise ValueError(
            f"Model '{model_type}' has only {complete_n} complete rows "
            f"(minimum {min_observations})."
        )

    print(f"Running model: {model_type}")
    print(get_model_description(model_type))
    results = fit_and_summarize(df, model_type=model_type, subset=subset)
    evaluation = evaluate_model_fit(results["fit_stats"])

    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = "" if overwrite else f"_{_to_timestamp()}"
    prefix = f"{_build_output_prefix(panel_level, model_type, subset)}{timestamp}"

    estimates_path = output_dir / f"{prefix}_estimates.csv"
    fit_stats_path = output_dir / f"{prefix}_fit_stats.csv"
    diagnostics_path = output_dir / f"{prefix}_diagnostics.json"
    manifest_path = output_dir / f"{prefix}_manifest.json"

    results["estimates"].to_csv(estimates_path, index=False)
    if isinstance(results["fit_stats"], pd.DataFrame):
        results["fit_stats"].to_csv(fit_stats_path)
    else:
        fit_df = pd.DataFrame.from_dict(results["fit_stats"], orient="index")
        fit_df.to_csv(fit_stats_path)

    fit_summary = summarize_fit(evaluation)
    artifacts: Dict[str, Any] = {
        "command": "run_sem_estimation.py",
        "input_path": str(input_path),
        "panel_level": panel_level,
        "model_type": model_type,
        "subset": subset,
        "sample_size": int(results["sample_size"]),
        "completed_rows": int(complete_n),
        "fit_summary": fit_summary,
    }
    diagnostics_path.write_text(
        json.dumps(
            {
                "evaluation": evaluation,
                "artifacts": artifacts,
            },
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    manifest_path.write_text(
        json.dumps(
            {
                "inputs": {
                    "input_path": str(input_path),
                    "required_variables": required_vars,
                    "all_columns": sorted(df.columns.tolist()),
                },
                "outputs": {
                    "estimates": str(estimates_path),
                    "fit_stats": str(fit_stats_path),
                    "diagnostics": str(diagnostics_path),
                },
                "run_info": {
                    "model_type": model_type,
                    "subset": subset,
                    "panel_level": panel_level,
                    "sample_size": int(results["sample_size"]),
                    "completed_rows": int(complete_n),
                    "created_utc": datetime.now(timezone.utc).isoformat(),
                },
            },
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )

    print(f"\nWrote estimation outputs:\n- {estimates_path}\n- {fit_stats_path}\n- {diagnostics_path}\n- {manifest_path}")
    print("\nFit summary:")
    print(fit_summary)
    return EstimationArtifacts(
        estimates_path=estimates_path,
        fit_stats_path=fit_stats_path,
        diagnostics_path=diagnostics_path,
        manifest_path=manifest_path,
    )


def _parse_args(args: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Estimate a SEM model over adapter outputs created in Phase 1."
        )
    )
    parser.add_argument(
        "--panel-level",
        choices=["disaster", "county", "city", "state"],
        default="disaster",
        help="Panel level to estimate (default: disaster).",
    )
    parser.add_argument(
        "--model",
        default="adapter_progress_rate",
        help=(
            "Model key from capacity_sem.models.sem_specifications."
            " Use --list-models to see all."
        ),
    )
    parser.add_argument(
        "--subset",
        choices=["all", "state", "local"],
        default="all",
        help="Subset filter (state/local/all).",
    )
    parser.add_argument(
        "--input",
        default=None,
        help="Override input CSV. Defaults to default adapter output path.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Output directory for SEM results.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing default output files with the same model prefix.",
    )
    parser.add_argument(
        "--min-observations",
        default=30,
        type=int,
        help="Minimum complete observations required before fitting.",
    )
    parser.add_argument(
        "--list-models",
        action="store_true",
        help="Print available model keys and exit.",
    )
    parser.add_argument(
        "--batch",
        nargs="+",
        default=None,
        metavar="MODEL",
        help="Run multiple models and write a comparison table.",
    )

    return parser.parse_args(args=args)


def _list_models() -> None:
    print("Available SEM model keys (capacity_sem.models.sem_specifications):")
    for model_type, desc in sorted(MODEL_REGISTRY.items()):
        print(f"  - {model_type}: {desc.split('\\n')[0]}")


def run_batch(
    input_path: Path,
    panel_level: str,
    model_types: List[str],
    subset: str,
    output_dir: Path,
    min_observations: int,
) -> int:
    """Run multiple models and write a comparison table."""
    output_dir.mkdir(parents=True, exist_ok=True)
    comparison_rows: List[Dict[str, Any]] = []

    for model_type in model_types:
        if model_type not in MODEL_REGISTRY:
            print(f"\nSKIP unknown model: {model_type}")
            continue
        print(f"\n{'='*60}")
        print(f"MODEL: {model_type}")
        print(f"{'='*60}")
        try:
            artifacts = run_estimation(
                input_path=input_path,
                panel_level=panel_level,
                model_type=model_type,
                subset=subset,
                overwrite=True,
                output_dir=output_dir,
                min_observations=min_observations,
            )
            diag = json.loads(artifacts.diagnostics_path.read_text())
            ev = diag.get("evaluation", {})
            art = diag.get("artifacts", {})
            comparison_rows.append(
                {
                    "model": model_type,
                    "sample_size": art.get("sample_size", ""),
                    "dof": ev.get("dof", ""),
                    "chi2": ev.get("chi2", ""),
                    "p_value": ev.get("p_value", ""),
                    "cfi": ev.get("cfi", ""),
                    "tli": ev.get("tli", ""),
                    "rmsea": ev.get("rmsea", ""),
                    "aic": ev.get("aic", ""),
                    "bic": ev.get("bic", ""),
                    "status": "ok",
                }
            )
        except Exception as e:
            print(f"  FAILED: {e}")
            comparison_rows.append(
                {"model": model_type, "status": f"error: {e}"}
            )

    if comparison_rows:
        comp_df = pd.DataFrame(comparison_rows)
        ts = _to_timestamp()
        comp_path = output_dir / f"batch_comparison_{ts}.csv"
        comp_df.to_csv(comp_path, index=False)
        print(f"\n{'='*60}")
        print(f"BATCH COMPARISON: {comp_path}")
        print(f"{'='*60}")
        print(comp_df.to_string(index=False))

    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    ns = _parse_args(argv)
    if ns.list_models:
        _list_models()
        return 0

    panel_level = ns.panel_level
    input_path = Path(ns.input) if ns.input else _default_input_path(panel_level)
    output_dir = Path(ns.output_dir)

    if ns.batch:
        return run_batch(
            input_path=input_path,
            panel_level=panel_level,
            model_types=ns.batch,
            subset=ns.subset,
            output_dir=output_dir,
            min_observations=ns.min_observations,
        )

    run_estimation(
        input_path=input_path,
        panel_level=panel_level,
        model_type=ns.model,
        subset=ns.subset,
        overwrite=ns.overwrite,
        output_dir=output_dir,
        min_observations=ns.min_observations,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
